import psycopg2
import os
from dotenv import load_dotenv

load_dotenv()

DB_HOST = os.getenv("DB_HOST", "localhost")
DB_PORT = os.getenv("DB_PORT", "5432")
DB_NAME = os.getenv("DB_NAME", "omniquery")
DB_USER = os.getenv("DB_USER", "postgres")
DB_PASSWORD = os.getenv("DB_PASSWORD", "postgres")

def apply_migrations():
    print("Connecting to database...")
    conn = psycopg2.connect(
        host=DB_HOST,
        port=DB_PORT,
        dbname=DB_NAME,
        user=DB_USER,
        password=DB_PASSWORD
    )
    conn.autocommit = True
    cursor = conn.cursor()

    print("Applying missing indexes generated by OmniQuery DBRE...")
    queries = [
        "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_orders_customer_id ON orders (customer_id);",
        "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_orders_status ON orders (status);"
    ]
    
    for q in queries:
        try:
            print(f"Executing: {q}")
            cursor.execute(q)
            print("Success.")
        except Exception as e:
            print(f"Error applying migration: {e}")
            
    print("Migrations applied successfully.")
    cursor.close()
    conn.close()

if __name__ == "__main__":
    apply_migrations()
